/* ============== Shared finding data + OWASP catalog ============== */

const OWASP_TOP10 = [
  { id:'A01:2021', name:'Broken Access Control',                    short:'Access Control' },
  { id:'A02:2021', name:'Cryptographic Failures',                   short:'Crypto Failures' },
  { id:'A03:2021', name:'Injection',                                short:'Injection' },
  { id:'A04:2021', name:'Insecure Design',                          short:'Insecure Design' },
  { id:'A05:2021', name:'Security Misconfiguration',                short:'Misconfiguration' },
  { id:'A06:2021', name:'Vulnerable and Outdated Components',       short:'Vuln Components' },
  { id:'A07:2021', name:'Identification and Authentication Failures', short:'Auth Failures' },
  { id:'A08:2021', name:'Software and Data Integrity Failures',     short:'Integrity Failures' },
  { id:'A09:2021', name:'Security Logging and Monitoring Failures', short:'Logging Failures' },
  { id:'A10:2021', name:'Server-Side Request Forgery (SSRF)',       short:'SSRF' },
];

const FINDINGS = [
  {
    id: 'FND-1042',
    title: 'SQL Injection on /api/v2/users/search',
    project: 'PRJ-001 · BSI Core Infra VA — Q2',
    application: 'BSI - Infra',
    place: 'Web Application',
    url: 'https://infra.bsi.example.com/api/v2/users/search?q=admin',
    cvss: 9.8,
    category: 'A03:2021',
    status: 'Open',
    found: '2026-05-11',
    pic: 'Sarah Park',
    description: 'The `q` parameter on the `/api/v2/users/search` endpoint concatenates user input directly into a backend SQL query without parameterisation. A blind boolean-based payload (`\' OR 1=1 --`) confirmed the database identity and version (MySQL 8.0.32).',
    impact: 'An unauthenticated attacker can enumerate the entire `users` table, including password hashes, email addresses, and MFA seeds. Time-based payloads suggest full DBA privileges on the service account, allowing arbitrary read/write across all schemas.',
    recommendation: 'Replace string concatenation with prepared statements / parameterised queries (e.g. `?` placeholders in JDBC). Validate `q` against an allow-list of alphanumeric characters. Deploy WAF rule OWASP CRS 942-100 in blocking mode. Rotate the `bsi_api` DB account and restrict to least-privilege SELECT on the `users_search_v` view.',
  },
  {
    id: 'FND-1041',
    title: 'Stored XSS in profile "About me" field',
    project: 'PRJ-001 · BSI Core Infra VA — Q2',
    application: 'BSI - Infra',
    place: 'Web Application',
    url: 'https://infra.bsi.example.com/profile/edit',
    cvss: 7.5,
    category: 'A03:2021',
    status: 'On Progress',
    found: '2026-05-10',
    pic: 'Sarah Park',
    description: 'The profile "About me" textarea persists HTML and JavaScript verbatim and renders it on the profile view without encoding. Payload `<img src=x onerror=alert(document.cookie)>` executed in another user\'s session.',
    impact: 'An attacker can craft a malicious profile that runs arbitrary JS in any visitor\'s browser, including admins viewing the user roster. Session cookies are not HttpOnly, allowing complete account takeover.',
    recommendation: 'Server-side: encode all user-supplied HTML on render (use OWASP Java Encoder, `<c:out>` or framework default). Client-side: switch to a strict CSP (`default-src \'self\'; script-src \'self\'`). Mark session cookies `HttpOnly` and `SameSite=Lax`.',
  },
  {
    id: 'FND-1040',
    title: 'IDOR — modify any user via PUT /api/users/{id}',
    project: 'PRJ-005 · KTB D-Net Interface VAPT',
    application: 'KTB - D-Net Interface',
    place: 'Web Application',
    url: 'https://dnet.ktb.example.com/api/users/4711',
    cvss: 8.1,
    category: 'A01:2021',
    status: 'Open',
    found: '2026-05-09',
    pic: 'Budi',
    description: 'The endpoint `PUT /api/users/{id}` accepts the path-parameter user ID without verifying the caller owns or has rights to that resource. A standard user could submit a PUT with another user\'s ID and modify their email and role.',
    impact: 'Privilege escalation to administrator: an attacker with a baseline account can set `role: "admin"` on their own user object, or change another user\'s email to one they control and trigger a password reset.',
    recommendation: 'Add an ownership check: the `{id}` in the path MUST equal `request.user.id`, OR the caller must hold the `admin:users.write` scope. Reject `role` field in PUT requests from non-admin contexts. Add an audit log entry for every user mutation.',
  },
  {
    id: 'FND-1039',
    title: 'Outdated nginx 1.18.0 — CVE-2021-23017',
    project: 'PRJ-001 · BSI Core Infra VA — Q2',
    application: 'BSI - Infra',
    place: 'Server',
    url: 'tcp://10.42.18.7:443',
    cvss: 7.7,
    category: 'A06:2021',
    status: 'Open',
    found: '2026-05-08',
    pic: 'Abu Rizal Mahdi',
    description: 'The web tier runs nginx 1.18.0 which is vulnerable to CVE-2021-23017 (off-by-one in the DNS resolver). Public PoC exists.',
    impact: 'Remote DoS and potentially RCE on the nginx worker process if the resolver directive is configured to query attacker-controlled DNS.',
    recommendation: 'Upgrade nginx to 1.24.0 or later. Pin the resolver to a trusted internal DNS (e.g. 10.42.0.53) and remove resolver directives that accept dynamic upstreams.',
  },
  {
    id: 'FND-1038',
    title: 'Hard-coded API key in Android APK',
    project: 'PRJ-003 · KTB HRIS Mobile Pentest',
    application: 'KTB - HRIS',
    place: 'Mobile App',
    url: 'apk://com.ktb.hris/assets/config.json',
    cvss: 8.6,
    category: 'A02:2021',
    status: 'Acceptance',
    found: '2026-05-06',
    pic: 'Nur Hasbullah M.',
    description: 'The KTB HRIS APK ships an `assets/config.json` containing a production Firebase service-account key with read/write access to all Firestore collections. Extraction takes ~15 seconds with `apktool`.',
    impact: 'Anyone with the APK (publicly distributed) can read and modify all HRIS data — payroll, KPIs, leave balances — bypassing all backend authorisation.',
    recommendation: 'Remove the service-account key from the bundle. Replace with short-lived OAuth tokens minted by the backend after user login. Rotate the leaked key immediately. Enable Firestore Security Rules requiring `request.auth.uid != null` on all collections.',
  },
  {
    id: 'FND-1037',
    title: 'Insecure cleartext traffic to /api/booking',
    project: 'PRJ-003 · KTB HRIS Mobile Pentest',
    application: 'KTB - HRIS',
    place: 'Mobile App',
    url: 'http://booking.ktb.example.com/api/booking',
    cvss: 6.5,
    category: 'A02:2021',
    status: 'On Progress',
    found: '2026-05-05',
    pic: 'Nur Hasbullah M.',
    description: '`AndroidManifest.xml` declares `android:usesCleartextTraffic="true"` and the booking screen calls `http://` (not `https://`). MITM proxy captured leave-request payloads in plaintext.',
    impact: 'Anyone on the same Wi-Fi (corporate hotspot, hotel, café) can read and modify booking requests — leave dates, manager email, approval tokens.',
    recommendation: 'Set `android:usesCleartextTraffic="false"`. Migrate all booking endpoints to HTTPS with a network-security-config that pins the corporate CA. Add HSTS at the gateway.',
  },
  {
    id: 'FND-1036',
    title: 'Verbose error reveals stack trace + DB schema',
    project: 'PRJ-002 · MMKSI Microsite Pentest',
    application: 'MMKSI - Microsite',
    place: 'Web Application',
    url: 'https://microsite.mmksi.example.com/contact?id=abc',
    cvss: 4.3,
    category: 'A05:2021',
    status: 'On Progress',
    found: '2026-05-03',
    pic: 'Sarah Park',
    description: 'Submitting a non-numeric `id` to `/contact` triggers an unhandled exception. The 500 response includes the full Spring stack trace plus the SQL query referencing the `lead_contacts` table.',
    impact: 'Information disclosure: attackers learn the framework version (Spring Boot 2.7.4 — known CVEs), the data schema, and the file layout of the application server.',
    recommendation: 'Disable detailed error pages in production (`server.error.include-stacktrace=never`). Return a generic 400 with a correlation ID. Log full traces server-side only.',
  },
  {
    id: 'FND-1035',
    title: 'Default Tomcat manager credentials accessible',
    project: 'PRJ-004 · MMKSI VTS Web Audit',
    application: 'MMKSI - VTS',
    place: 'Server',
    url: 'https://vts.mmksi.example.com/manager/html',
    cvss: 9.1,
    category: 'A05:2021',
    status: 'Open',
    found: '2026-05-02',
    pic: 'John Lee',
    description: '`/manager/html` is reachable from the public internet and accepts `tomcat:tomcat`. An attacker who deploys a WAR achieves code execution as the `tomcat` user.',
    impact: 'Full remote code execution on the application server, leading to lateral movement into the database tier and the internal AD environment.',
    recommendation: 'Restrict `/manager/html` to the management VLAN via `<Valve>` RemoteAddrValve. Remove the default `tomcat` account from `tomcat-users.xml`. Enforce strong, unique credentials and 2FA for the manager UI. Audit deployed WARs for backdoors.',
  },
  {
    id: 'FND-1034',
    title: 'Missing CSRF token on state-changing POSTs',
    project: 'PRJ-002 · MMKSI Microsite Pentest',
    application: 'MMKSI - Microsite',
    place: 'Web Application',
    url: 'https://microsite.mmksi.example.com/account/email',
    cvss: 6.8,
    category: 'A01:2021',
    status: 'Closed',
    found: '2026-04-28',
    pic: 'Sarah Park',
    description: '`POST /account/email` and `POST /account/password` do not validate a CSRF token. SameSite cookie attribute is `None`. Cross-site form submission updates the victim\'s email.',
    impact: 'An attacker who hosts a malicious page can change a logged-in victim\'s account email to one they control, then trigger a password reset and take over the account.',
    recommendation: 'Enable Spring Security CSRF protection (`http.csrf().csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())`). Set `SameSite=Lax` on session cookies. Require re-authentication for email change.',
  },
  {
    id: 'FND-1033',
    title: 'No rate-limit on /api/login enables credential stuffing',
    project: 'PRJ-004 · MMKSI VTS Web Audit',
    application: 'MMKSI - VTS',
    place: 'Web Application',
    url: 'https://vts.mmksi.example.com/api/login',
    cvss: 5.9,
    category: 'A07:2021',
    status: 'On Progress',
    found: '2026-04-26',
    pic: 'John Lee',
    description: '500 sequential login attempts against `/api/login` from one IP completed in 8 s with no challenge, throttle, or lockout. Successful logins are distinguishable by HTTP 200 vs 401.',
    impact: 'Attackers can run credential-stuffing attacks at scale using leaked password dumps and compromise any reused passwords across the user base.',
    recommendation: 'Add rate limiting at the gateway (e.g. 5 attempts / 5 min / IP, plus per-account counter). Introduce CAPTCHA after 3 failed attempts. Implement account lockout with exponential backoff. Subscribe to a leaked-password feed (HIBP API) and force reset on matches.',
  },
  {
    id: 'FND-1032',
    title: 'Sensitive log file world-readable',
    project: 'PRJ-008 · KTB Karoseri Portal VAPT',
    application: 'KTB - Karoseri Portal',
    place: 'Server',
    url: 'file:///var/log/app/karoseri-prod.log',
    cvss: 5.3,
    category: 'A09:2021',
    status: 'Open',
    found: '2026-04-24',
    pic: 'Sarah Park',
    description: '`/var/log/app/karoseri-prod.log` is mode `0644` and contains full request bodies, including bearer tokens during the auth flow. Any local user can read it.',
    impact: 'Local-attacker token theft and replay. Lateral access from a compromised low-privilege process into the application as any user that has logged in recently.',
    recommendation: 'Set log files to mode `0640` with group `app-readers` only. Filter `Authorization`, `Cookie`, and `password` fields from log output (use a logback `PatternLayout` mask). Rotate any leaked tokens.',
  },
  {
    id: 'FND-1031',
    title: 'SSRF via webhook URL on integration settings',
    project: 'PRJ-005 · KTB D-Net Interface VAPT',
    application: 'KTB - D-Net Interface',
    place: 'Web Application',
    url: 'https://dnet.ktb.example.com/settings/webhook',
    cvss: 8.6,
    category: 'A10:2021',
    status: 'Open',
    found: '2026-04-22',
    pic: 'Budi',
    description: 'The webhook URL field accepts internal and metadata URLs. Setting it to `http://169.254.169.254/latest/meta-data/iam/security-credentials/` and triggering a test call returned AWS IAM credentials in the response body.',
    impact: 'Credential theft from the EC2 metadata service. The recovered IAM role has `s3:*` on the customer-data bucket — full read/write of all customer records.',
    recommendation: 'Use IMDSv2 (require session tokens) on every EC2 instance. Block egress from app servers to `169.254.169.254` and RFC1918 ranges at the security-group level. On the application side, validate webhook URLs against an allow-list of customer domains and reject IPs.',
  },
  {
    id: 'FND-1030',
    title: 'Unsigned in-app update mechanism',
    project: 'PRJ-003 · KTB HRIS Mobile Pentest',
    application: 'KTB - HRIS',
    place: 'Mobile App',
    url: 'https://hris.ktb.example.com/mobile/update.json',
    cvss: 8.1,
    category: 'A08:2021',
    status: 'Open',
    found: '2026-04-20',
    pic: 'Nur Hasbullah M.',
    description: 'The mobile auto-update flow downloads an APK from a URL listed in `update.json` and installs it. The APK is not signature-verified before install and the manifest URL is fetched over plain HTTPS without certificate pinning.',
    impact: 'An attacker performing TLS interception (compromised CA, hostile network) can serve a malicious APK that the device will install, granting full control of HRIS sessions on the device.',
    recommendation: 'Verify the downloaded APK against an embedded public key before invoking the installer. Pin the certificate of the update host. Sign `update.json` and verify the signature in-app.',
  },
  {
    id: 'FND-1029',
    title: 'No audit log on role change',
    project: 'PRJ-010 · KTB Supplier Portal VA Infra',
    application: 'KTB - Supplier Portal',
    place: 'Web Application',
    url: 'https://supplier.ktb.example.com/admin/users',
    cvss: 3.7,
    category: 'A09:2021',
    status: 'Closed',
    found: '2026-04-15',
    pic: 'Budi',
    description: 'Promoting a user to `admin` produces no log entry in the application or the SIEM. Demotions, role removals, and account disablement are also silent.',
    impact: 'Insider abuse and post-compromise privilege escalation cannot be detected or attributed. Forensics following an incident is impossible for any user-management action.',
    recommendation: 'Emit a structured audit event for every user/role mutation with actor, target, before/after state, source IP, and request ID. Forward to the SIEM with a 1-year retention. Add a dashboard tile for "role changes / 24 h".',
  },
  {
    id: 'FND-1028',
    title: 'Weak password policy (min length 6)',
    project: 'PRJ-002 · MMKSI Microsite Pentest',
    application: 'MMKSI - Microsite',
    place: 'Web Application',
    url: 'https://microsite.mmksi.example.com/signup',
    cvss: 4.8,
    category: 'A07:2021',
    status: 'Acceptance',
    found: '2026-04-12',
    pic: 'Sarah Park',
    description: 'Signup accepts a 6-character password with no complexity, no breached-password check, and no MFA. `password` and `123456` pass validation.',
    impact: 'Trivial brute force of guessable passwords. Customer accounts are easily compromised, leading to PII exposure in saved bookings.',
    recommendation: 'Adopt NIST SP 800-63B: minimum 12 characters, allow long passphrases, check against HIBP top-100k, no forced rotation. Offer TOTP MFA on all customer accounts.',
  },
  {
    id: 'FND-1027',
    title: 'TLS 1.0/1.1 enabled on management interface',
    project: 'PRJ-001 · BSI Core Infra VA — Q2',
    application: 'BSI - Infra',
    place: 'Server',
    url: 'tcp://mgmt.bsi.example.com:8443',
    cvss: 5.9,
    category: 'A02:2021',
    status: 'Closed',
    found: '2026-04-08',
    pic: 'Abu Rizal Mahdi',
    description: 'The internal management interface negotiates TLS 1.0 and TLS 1.1 with deprecated cipher suites (`TLS_RSA_WITH_3DES_EDE_CBC_SHA`).',
    impact: 'BEAST, Lucky13, and Sweet32 are practical against these versions and ciphers. Confidentiality of admin sessions cannot be relied upon.',
    recommendation: 'Disable TLS 1.0 and 1.1 on every listener. Restrict cipher suites to TLS 1.2/1.3 AEAD suites (`ECDHE_*_AES_GCM_*`, `ECDHE_*_CHACHA20_*`). Re-test with `testssl.sh` after the change.',
  },
];
